name: AutoDocGPT

description: AutoDocGPT automates README generation for Next.js and React projects, using GPT to create concise and tailored documentation.

author: Priyam More

branding:
  icon: "book-open"
  color: "red"

inputs:
  email:
    description: The committer's email address.
    required: true
    default: ${{ github.actor }}@users.noreply.github.com
  name:
    description: The committer's name.
    required: true
    default: ${{ github.actor }}

runs:
  using: "docker"
  image: "Dockerfile"
